# Generated by Django 4.1.7 on 2023-04-02 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogproject', '0016_profile_fb_url_profile_github_url_profile_ins_url_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='fb_url',
            new_name='facebook_url',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='ins_url',
        ),
        migrations.AddField(
            model_name='profile',
            name='instagram_url',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
